### ISSUE TITLE
Please don't make your users generate keys before testing

### ISSUE THREAD

**Issue by tomjaguarpaw** [avieth/diplomacy-server#4]
It's a huge impediment to users trying out your software if you force them to generate SSL keys.  I'm sticking at this because I'm particularly interested, but I can image 50% of users will just give up.

**Comment by avieth** [comment]
What's the alternative? I don't want to put a default certificate and key into the repository. If someone uses it to start the server, then they have insecure games, and we may as well ditch the secure server and use normal http.

**Comment by tomjaguarpaw** [comment]
Yes, I would just allow HTTP with a `--yes-i-really-want-an-insecure-http-server` flag.  Otherwise people are going to find it _very_ irritating to try out your game.

**Comment by avieth** [comment]
99693d1368f6bf904a786a2459c5e7bc9dd0b853

HTTPS is opt-in. Though I suppose the proper way to get a secure server is to put nginx or similar in front of this server.

I left HTTPS in because this is a weird spot: HTTP is fine for this application (don't invite your packet-sniffing friends) but browsers are increasingly frowning upon HTTP (rightly so). I think the rule is: if it has ever visited this domain in HTTPS then it won't allow you to visit it insecure, unless you know the secret trick to remove the rule (how do you do this on a phone???). But then even if you do use HTTPS, you'll get the warning about a self-signed certificate, unless you go through all the trouble of pointing your domain to the address on the local network where the game is running...

Anyway, it's easier to get going now. I may get around to making the UI just good enough to not discourage everybody but me.
